# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_m2modelbase1_m2modelbase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app2.Item')),
                ('derived_col_1', models.CharField(blank=True, max_length=400, null=True)),
                ('derived_col_2', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app2.item',),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
