# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_ingredient_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deriveditem',
            options={'verbose_name': 'DerivedItem cls'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Review content'),
        ),
    ]
