# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20160912_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='default_name', max_length=400, verbose_name='Ingredient'),
            preserve_default=False,
        ),
    ]
