# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_info', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='items',
        ),
        migrations.AddField(
            model_name='composition',
            name='ing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Ingredient'),
        ),
        migrations.AddField(
            model_name='composition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Item'),
        ),
    ]
