# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_auto_20160913_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='items',
            field=models.ManyToManyField(related_name='ings', through='app2.Composition', to='app2.Item'),
        ),
    ]
