# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_ingredient_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='short_info',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
