# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
