# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Products',
            new_name='products',
        ),
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together=set([('ing', 'product')]),
        ),
    ]
