# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20161003_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Numbers of product in the order item'),
        ),
    ]
